### ISSUE TITLE
Πρόβλημα με White / Dark mode

### ISSUE THREAD

**Issue by ervans589** [UniStudents/unistudents#14]
Ένα πρόβλημα (bug) που παρατήρησα ήταν:
Όταν το σύστημα της σχολής δεν ανταποκρίνεται και γίνεται η αυτόματη αποσύνδεση του χρήστη, η επανασύυνδεσή του οδηγεί σε εφαρμογή του white mode ακόμη και όταν το default theme πριν την αποσύνδεση ήταν το dark mode.
Ευχαριστώ!

**Comment by NickSklA** [comment]
Σε ευχαριστούμε για την αναφορά! Κανονικά δε θα έπρεπε να γίνεται αποσύνδεση όταν δεν αποκρίνεται το σύστημα της σχολής σου. Μπορείς να μας πεις σε ποιο πανεπιστήμιο σπουδάζεις να το κοιτάξουμε;

**Comment by ervans589** [comment]
Καλησπέρα,
Σπουδάζω στο Πανεπιστήμιο Δυτικής Αττικής. Να διευκρινίσω ότι η αποσύνδεση
από την εφαρμογή γίνεται όταν και η ιστοσελίδα ταυτοποίησης του
πανεπιστημίου δεν ανταποκρίνεται (βγάζει σφάλμα λανθασμένου κωδικού -
συμβαίνει σε περιόδους αναβάθμισης ή συντήρησης του φοιτητολογίου). Άρα
είναι λογικό να με αποσυνδέει η εφαρμογή λόγω λανθασμένου κωδικού. Δεν
νομίζω ότι υπάρχει λόγος να ανησυχείτε για αυτό ;).
Το πρόβλημα είναι με την εναλλαγή σε white mode όταν καταφέρω να
επανασυνδεθώ.
Ευχαριστώ!

**Comment by NickSklA** [comment]
Μια χαρά τότε! Όσον αναφορά την εναλλαγή σε white mode θα ετοιμάσουμε σύντομα νέο update. Σε ευχαριστούμε και πάλι για την αναφορά ✌️

**Comment by ervans589** [comment]
Έγινε! Ευχαριστώ!
